package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if err := validateFile(file); err != nil {
				return fmt.Errorf("%s: %w", file.Desc.Path(), err)
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func validateFile(file *protogen.File) error {
	if file.Desc.Syntax() != protoreflect.Proto2 {
		return fmt.Errorf("proto3 syntax is not supported (only proto2)")
	}
	if len(file.Services) > 0 {
		return fmt.Errorf("services are not supported")
	}
	if len(file.Extensions) > 0 {
		return fmt.Errorf("extension fields are not supported")
	}
	for _, msg := range file.Messages {
		if err := validateMessage(msg); err != nil {
			return err
		}
	}
	return nil
}

func validateMessage(msg *protogen.Message) error {
	for _, field := range msg.Fields {
		if field.Desc.Kind() == protoreflect.GroupKind {
			return fmt.Errorf("group fields are not supported (field '%s' in message '%s')",
				field.Desc.Name(), msg.Desc.Name())
		}
	}
	for _, nested := range msg.Messages {
		if err := validateMessage(nested); err != nil {
			return err
		}
	}
	return nil
}

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	filename := strings.TrimSuffix(file.Desc.Path(), ".proto") + "_arena.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-arena. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsMath := false
	needsFmt := false
	for _, msg := range file.Messages {
		for _, field := range msg.Fields {
			k := field.Desc.Kind()
			if k == protoreflect.FloatKind || k == protoreflect.DoubleKind {
				needsMath = true
			}
			if field.Desc.Cardinality() == protoreflect.Required {
				needsFmt = true
			}
		}
	}

	g.P("import (")
	if needsFmt {
		g.P("\"fmt\"")
	}
	if needsMath {
		g.P("\"math\"")
	}
	g.P("\"github.com/limpo1989/arena\"")
	g.P("\"github.com/limpo1989/arena/protowire\"")
	g.P(")")
	g.P()

	for _, enum := range file.Enums {
		genEnum(g, enum)
	}

	for _, msg := range file.Messages {
		genMessage(g, msg)
	}
}

// ---------------------------------------------------------------------------
// Enum
// ---------------------------------------------------------------------------

func genEnum(g *protogen.GeneratedFile, enum *protogen.Enum) {
	g.P("type ", enum.GoIdent.GoName, " int32")
	g.P()
	g.P("const (")
	for _, v := range enum.Values {
		g.P(v.GoIdent.GoName, " ", enum.GoIdent.GoName, " = ", v.Desc.Number())
	}
	g.P(")")
	g.P()
}

// ---------------------------------------------------------------------------
// Message
// ---------------------------------------------------------------------------

func genMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName

	// Oneof interfaces and wrappers (before struct)
	for _, oneof := range msg.Oneofs {
		genOneofInterface(g, msg, oneof)
	}

	// Struct
	g.P("type ", msgName, " struct {")
	for _, field := range msg.Fields {
		if field.Oneof != nil {
			continue // oneof variants are handled via the interface field
		}
		g.P(field.GoName, " ", fieldType(field))
	}
	for _, oneof := range msg.Oneofs {
		g.P(oneof.GoName, " is", msgName, "_", oneof.GoName)
	}
	g.P("}")
	g.P()

	// Getters
	genGetters(g, msg)

	// Size
	genSize(g, msg)

	// MarshalTo
	genMarshalTo(g, msg)

	// Marshal
	g.P("func (m *", msgName, ") Marshal() ([]byte, error) {")
	g.P("buf := make([]byte, m.Size())")
	g.P("n, err := m.MarshalTo(buf)")
	g.P("if err != nil { return nil, err }")
	g.P("return buf[:n], nil")
	g.P("}")
	g.P()

	// Unmarshal
	genUnmarshal(g, msg)
}

func genOneofInterface(g *protogen.GeneratedFile, msg *protogen.Message, oneof *protogen.Oneof) {
	msgName := msg.GoIdent.GoName
	ifaceName := "is" + msgName + "_" + oneof.GoName

	g.P("type ", ifaceName, " interface { ", ifaceName, "() }")
	for _, field := range oneof.Fields {
		wrapperName := msgName + "_" + field.GoName
		valType := elemType(field)
		g.P("type ", wrapperName, " struct { Value ", valType, " }")
		g.P("func (*", wrapperName, ") ", ifaceName, "() {}")
	}
	g.P()
}

// ---------------------------------------------------------------------------
// Field type mapping
// ---------------------------------------------------------------------------

func fieldType(field *protogen.Field) string {
	desc := field.Desc
	if desc.IsMap() {
		return "*arena.Map[" + elemType(field.Message.Fields[0]) + "," + elemType(field.Message.Fields[1]) + "]"
	}
	if desc.IsList() {
		return "[]" + elemType(field)
	}
	if desc.HasOptionalKeyword() || desc.Cardinality() == protoreflect.Required {
		if desc.Kind() == protoreflect.MessageKind {
			return "*" + string(field.Message.GoIdent.GoName)
		}
		return "*" + elemType(field)
	}
	if desc.Kind() == protoreflect.MessageKind && !desc.IsMap() {
		return "*" + string(field.Message.GoIdent.GoName)
	}
	return elemType(field)
}

func elemType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		if field.Enum != nil {
			return string(field.Enum.GoIdent.GoName)
		}
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.EnumKind:
		return string(field.Enum.GoIdent.GoName)
	case protoreflect.MessageKind:
		return "*" + string(field.Message.GoIdent.GoName)
	default:
		return "interface{}"
	}
}

// ---------------------------------------------------------------------------
// Getters
// ---------------------------------------------------------------------------

func genGetters(g *protogen.GeneratedFile, msg *protogen.Message) {
	for _, field := range msg.Fields {
		desc := field.Desc
		goName := field.GoName

		if field.Oneof != nil {
			// Oneof variant getter
			msgName := msg.GoIdent.GoName
			valType := elemType(field)
			wrapperName := msgName + "_" + goName
			g.P("func (m *", msgName, ") Get", goName, "() ", valType, " {")
			g.P("if x, ok := m.", field.Oneof.GoName, ".(*", wrapperName, "); ok { return x.Value }")
			g.P("return ", defaultVal(field))
			g.P("}")
			g.P()
			continue
		}

		if desc.IsMap() {
			mapType := fieldType(field)
			g.P("func (m *", msg.GoIdent.GoName, ") Get", goName, "() ", mapType, " {")
			g.P("if m != nil { return m.", goName, " }")
			g.P("return nil")
			g.P("}")
			g.P()
			continue
		}

		if desc.IsList() {
			goType := "[]" + elemType(field)
			g.P("func (m *", msg.GoIdent.GoName, ") Get", goName, "() ", goType, " {")
			g.P("if m != nil { return m.", goName, " }")
			g.P("return nil")
			g.P("}")
			g.P()
			continue
		}

		goType := elemType(field)
		isPtr := desc.HasOptionalKeyword() || desc.Cardinality() == protoreflect.Required || desc.Kind() == protoreflect.MessageKind
		defVal := defaultVal(field)

		if isPtr {
			g.P("func (m *", msg.GoIdent.GoName, ") Get", goName, "() ", goType, " {")
			if desc.Kind() == protoreflect.MessageKind {
				g.P("if m != nil { return m.", goName, " }")
			} else {
				g.P("if m != nil && m.", goName, " != nil { return *m.", goName, " }")
			}
			g.P("return ", defVal)
			g.P("}")
		} else {
			g.P("func (m *", msg.GoIdent.GoName, ") Get", goName, "() ", goType, " {")
			g.P("if m != nil { return m.", goName, " }")
			g.P("return ", defVal)
			g.P("}")
		}
		g.P()

		if desc.HasOptionalKeyword() {
			g.P("func (m *", msg.GoIdent.GoName, ") Has", goName, "() bool {")
			g.P("return m != nil && m.", goName, " != nil")
			g.P("}")
			g.P()
		}
	}
}

func defaultVal(field *protogen.Field) string {
	desc := field.Desc
	if desc.HasDefault() {
		def := desc.Default()
		switch desc.Kind() {
		case protoreflect.StringKind:
			return "`" + def.String() + "`"
		case protoreflect.BytesKind:
			return "nil"
		case protoreflect.BoolKind:
			if def.Bool() {
				return "true"
			}
			return "false"
		case protoreflect.FloatKind:
			return fmt.Sprintf("float32(%v)", def.Float())
		case protoreflect.DoubleKind:
			return fmt.Sprintf("float64(%v)", def.Float())
		case protoreflect.EnumKind:
			if field.Enum != nil {
				for _, v := range field.Enum.Values {
					if v.Desc.Number() == def.Enum() {
						return string(v.GoIdent.GoName)
					}
				}
			}
			return fmt.Sprintf("%d", def.Enum())
		default:
			return fmt.Sprintf("%v", def.Interface())
		}
	}
	switch desc.Kind() {
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.StringKind:
		return `""`
	case protoreflect.BytesKind:
		return "nil"
	case protoreflect.MessageKind:
		return "nil"
	case protoreflect.EnumKind:
		if field.Enum != nil && len(field.Enum.Values) > 0 {
			return string(field.Enum.Values[0].GoIdent.GoName)
		}
		return "0"
	default:
		return "0"
	}
}

// ---------------------------------------------------------------------------
// Size
// ---------------------------------------------------------------------------

func genSize(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName
	g.P("func (m *", msgName, ") Size() (n int) {")
	seen := map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil {
			oneofName := field.Oneof.GoName
			if seen[oneofName] {
				continue
			}
			seen[oneofName] = true
			genOneofSize(g, msgName, field.Oneof)
			continue
		}
		genFieldSize(g, field)
	}
	g.P("return")
	g.P("}")
	g.P()
}

func genOneofSize(g *protogen.GeneratedFile, msgName string, oneof *protogen.Oneof) {
	g.P("switch x := m.", oneof.GoName, ".(type) {")
	for _, field := range oneof.Fields {
		wrapperName := msgName + "_" + field.GoName
		fn := int(field.Desc.Number())
		g.P("case *", wrapperName, ":")
		g.P("n += ", oneofFieldSizeExpr("x.Value", field, fn))
	}
	g.P("default: _ = x")
	g.P("}")
}

func oneofFieldSizeExpr(access string, field *protogen.Field, fn int) string {
	return fieldSizeExpr(access, field, fn, false)
}

func genFieldSize(g *protogen.GeneratedFile, field *protogen.Field) {
	desc := field.Desc
	fn := int(desc.Number())
	goName := field.GoName

	if desc.IsMap() {
		g.P("if m.", goName, " != nil {")
		g.P("m.", goName, ".All()(func(k ", mapKeyType(field), ", v ", mapValType(field), ") bool {")
		g.P("vv := v")
		g.P("entrySize := protowire.SizeOfVarint(uint64(", fn, "<<3|2))")
		g.P("entrySize += ", mapKeySizeExpr("k", field))
		g.P("entrySize += ", mapValSizeExpr("vv", field))
		g.P("n += entrySize + protowire.SizeOfVarint(uint64(entrySize))")
		g.P("return true")
		g.P("})")
		g.P("}")
		return
	}

	if desc.IsList() {
		if isScalar(field) && field.Desc.IsPacked() {
			g.P("if len(m.", goName, ") > 0 {")
			g.P("packedLen := 0")
			switch field.Desc.Kind() {
			case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
				g.P("packedLen = len(m.", goName, ") * 4")
			case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
				g.P("packedLen = len(m.", goName, ") * 8")
			case protoreflect.BoolKind:
				g.P("packedLen = len(m.", goName, ")")
			default:
				g.P("for _, v := range m.", goName, " { packedLen += ", scalarSizeExpr("v", field), " }")
			}
			g.P("n += protowire.SizeOfVarint(uint64(", fn, "<<3|2)) + protowire.SizeOfVarint(uint64(packedLen)) + packedLen")
			g.P("}")
		} else if isScalar(field) {
			g.P("for _, v := range m.", goName, " {")
			g.P("n += protowire.SizeOfVarint(uint64(", fn, "<<3|0)) + ", scalarSizeExpr("v", field))
			g.P("}")
		} else {
			g.P("for _, v := range m.", goName, " {")
			g.P("n += protowire.SizeOfVarint(uint64(", fn, "<<3|", wireOf(field), ")) + ", scalarSizeExpr("v", field))
			g.P("}")
		}
		return
	}

	isPtr := desc.HasOptionalKeyword() || desc.Cardinality() == protoreflect.Required || desc.Kind() == protoreflect.MessageKind
	access := "m." + goName
	if isPtr {
		g.P("if ", access, " != nil {")
	}
	g.P("n += ", fieldSizeExpr(access, field, fn, isPtr))
	if isPtr {
		g.P("}")
	}
}

func mapKeyType(field *protogen.Field) string {
	return elemType(field.Message.Fields[0])
}

func mapValType(field *protogen.Field) string {
	return elemType(field.Message.Fields[1])
}

func mapKeySizeExpr(k string, field *protogen.Field) string {
	kf := field.Message.Fields[0]
	return fieldSizeExpr(k, kf, 1, false)
}

func mapValSizeExpr(v string, field *protogen.Field) string {
	vf := field.Message.Fields[1]
	return fieldSizeExpr(v, vf, 2, false)
}

func isScalar(field *protogen.Field) bool {
	k := field.Desc.Kind()
	return k != protoreflect.StringKind && k != protoreflect.BytesKind && k != protoreflect.MessageKind
}

func wireOf(field *protogen.Field) int {
	switch field.Desc.Kind() {
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.Sint32Kind, protoreflect.Sint64Kind, protoreflect.BoolKind, protoreflect.EnumKind:
		return 0
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		return 1
	case protoreflect.StringKind, protoreflect.BytesKind, protoreflect.MessageKind:
		return 2
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		return 5
	default:
		return 2
	}
}

func scalarSizeExpr(v string, field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "1"
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.EnumKind:
		return "protowire.SizeOfVarint(uint64(" + v + "))"
	case protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		return "protowire.SizeOfVarint(protowire.EncodeZigZag(int64(" + v + ")))"
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		return "4"
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		return "8"
	case protoreflect.StringKind, protoreflect.BytesKind:
		return "protowire.SizeOfVarint(uint64(len(" + v + "))) + len(" + v + ")"
	default:
		return "0"
	}
}

func fieldSizeExpr(access string, field *protogen.Field, fn int, isPtr bool) string {
	prefix := ""
	if isPtr {
		prefix = "*"
	}
	wt := wireOf(field)
	tag := fmt.Sprintf("protowire.SizeOfVarint(uint64(%d<<3|%d))", fn, wt)

	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return tag + " + 1"
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.EnumKind:
		return tag + " + protowire.SizeOfVarint(uint64(" + prefix + access + "))"
	case protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		return tag + " + protowire.SizeOfVarint(protowire.EncodeZigZag(int64(" + prefix + access + ")))"
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		return fmt.Sprintf("protowire.SizeOfVarint(uint64(%d<<3|5)) + 4", fn)
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		return fmt.Sprintf("protowire.SizeOfVarint(uint64(%d<<3|1)) + 8", fn)
	case protoreflect.StringKind, protoreflect.BytesKind:
		return tag + " + protowire.SizeOfVarint(uint64(len(" + prefix + access + "))) + len(" + prefix + access + ")"
	case protoreflect.MessageKind:
		return tag + " + protowire.SizeOfVarint(uint64(" + access + ".Size())) + " + access + ".Size()"
	default:
		return "0"
	}
}

// ---------------------------------------------------------------------------
// MarshalTo
// ---------------------------------------------------------------------------

func genMarshalTo(g *protogen.GeneratedFile, msg *protogen.Message) {
	msgName := msg.GoIdent.GoName
	g.P("func (m *", msgName, ") MarshalTo(dAtA []byte) (int, error) {")
	g.P("i := 0")
	seen := map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil {
			oneofName := field.Oneof.GoName
			if seen[oneofName] {
				continue
			}
			seen[oneofName] = true
			genOneofMarshal(g, msgName, field.Oneof)
			continue
		}
		genFieldMarshal(g, field)
	}
	g.P("return i, nil")
	g.P("}")
	g.P()
}

func genOneofMarshal(g *protogen.GeneratedFile, msgName string, oneof *protogen.Oneof) {
	g.P("switch x := m.", oneof.GoName, ".(type) {")
	for _, field := range oneof.Fields {
		wrapperName := msgName + "_" + field.GoName
		fn := int(field.Desc.Number())
		g.P("case *", wrapperName, ":")
		genOneofVariantMarshal(g, field, fn, "x.Value")
	}
	g.P("default: _ = x")
	g.P("}")
}

func genOneofVariantMarshal(g *protogen.GeneratedFile, field *protogen.Field, fn int, access string) {
	switch field.Desc.Kind() {
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.BoolKind, protoreflect.EnumKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|0))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", access, "))")
	case protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|0))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], protowire.EncodeZigZag(int64(", access, ")))")
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|5))")
		genFixed32Marshal(g, access, field)
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|1))")
		genFixed64Marshal(g, access, field)
	case protoreflect.StringKind, protoreflect.BytesKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|2))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(len(", access, ")))")
		g.P("copy(dAtA[i:], ", access, ")")
		g.P("i += len(", access, ")")
	case protoreflect.MessageKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|2))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", access, ".Size()))")
		g.P(access, ".MarshalTo(dAtA[i:])")
		g.P("i += ", access, ".Size()")
	}
}

func genFixed32Marshal(g *protogen.GeneratedFile, access string, field *protogen.Field) {
	switch field.Desc.Kind() {
	case protoreflect.FloatKind:
		g.P("i += protowire.EncodeFixed32(dAtA[i:], math.Float32bits(", access, "))")
	case protoreflect.Sfixed32Kind:
		g.P("i += protowire.EncodeFixed32(dAtA[i:], uint32(", access, "))")
	default:
		g.P("i += protowire.EncodeFixed32(dAtA[i:], ", access, ")")
	}
}

func genFixed64Marshal(g *protogen.GeneratedFile, access string, field *protogen.Field) {
	switch field.Desc.Kind() {
	case protoreflect.DoubleKind:
		g.P("i += protowire.EncodeFixed64(dAtA[i:], math.Float64bits(", access, "))")
	case protoreflect.Sfixed64Kind:
		g.P("i += protowire.EncodeFixed64(dAtA[i:], uint64(", access, "))")
	default:
		g.P("i += protowire.EncodeFixed64(dAtA[i:], ", access, ")")
	}
}

func genFieldMarshal(g *protogen.GeneratedFile, field *protogen.Field) {
	desc := field.Desc
	fn := int(desc.Number())
	goName := field.GoName

	if desc.IsMap() {
		g.P("if m.", goName, " != nil {")
		g.P("m.", goName, ".All()(func(k ", mapKeyType(field), ", v ", mapValType(field), ") bool {")
		g.P("vv := v")
		g.P("entrySize := ", mapKeySizeExpr("k", field), " + ", mapValSizeExpr("vv", field))
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|2))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(entrySize))")
		genMapKeyMarshal(g, "k", field, 1)
		genMapValMarshal(g, "vv", field, 2)
		g.P("return true")
		g.P("})")
		g.P("}")
		return
	}

	if desc.IsList() {
		if isScalar(field) && field.Desc.IsPacked() {
			// Packed encoding
			g.P("if len(m.", goName, ") > 0 {")
			g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|2))")
			g.P("packedLen := 0")
			switch field.Desc.Kind() {
			case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
				g.P("packedLen = len(m.", goName, ") * 4")
			case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
				g.P("packedLen = len(m.", goName, ") * 8")
			case protoreflect.BoolKind:
				g.P("packedLen = len(m.", goName, ")")
			default:
				g.P("for _, v := range m.", goName, " { packedLen += ", scalarSizeExpr("v", field), " }")
			}
			g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(packedLen))")
			g.P("for _, v := range m.", goName, " {")
			genScalarMarshal(g, "v", field)
			g.P("}")
			g.P("}")
		} else if isScalar(field) {
			// Unpacked scalar
			g.P("for _, v := range m.", goName, " {")
			g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|0))")
			genScalarMarshal(g, "v", field)
			g.P("}")
		} else {
			// Unpacked (strings, bytes, messages)
			g.P("for _, v := range m.", goName, " {")
			g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|", wireOf(field), "))")
			if desc.Kind() == protoreflect.MessageKind {
				g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(v.Size()))")
				g.P("v.MarshalTo(dAtA[i:])")
				g.P("i += v.Size()")
			} else {
				g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(len(v)))")
				g.P("copy(dAtA[i:], v)")
				g.P("i += len(v)")
			}
			g.P("}")
		}
		return
	}

	isPtr := desc.HasOptionalKeyword() || desc.Cardinality() == protoreflect.Required || desc.Kind() == protoreflect.MessageKind
	access := "m." + goName
	if isPtr {
		g.P("if ", access, " != nil {")
	}

	prefix := ""
	if isPtr {
		prefix = "*"
	}

	switch desc.Kind() {
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.EnumKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|0))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", prefix, access, "))")
	case protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|0))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], protowire.EncodeZigZag(int64(", prefix, access, ")))")
	case protoreflect.BoolKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|0))")
		g.P("if ", prefix, access, " { dAtA[i] = 1; i++ } else { dAtA[i] = 0; i++ }")
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|5))")
		switch desc.Kind() {
		case protoreflect.FloatKind:
			g.P("i += protowire.EncodeFixed32(dAtA[i:], math.Float32bits(", prefix, access, "))")
		case protoreflect.Sfixed32Kind:
			g.P("i += protowire.EncodeFixed32(dAtA[i:], uint32(", prefix, access, "))")
		default:
			g.P("i += protowire.EncodeFixed32(dAtA[i:], ", prefix, access, ")")
		}
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|1))")
		switch desc.Kind() {
		case protoreflect.DoubleKind:
			g.P("i += protowire.EncodeFixed64(dAtA[i:], math.Float64bits(", prefix, access, "))")
		case protoreflect.Sfixed64Kind:
			g.P("i += protowire.EncodeFixed64(dAtA[i:], uint64(", prefix, access, "))")
		default:
			g.P("i += protowire.EncodeFixed64(dAtA[i:], ", prefix, access, ")")
		}
	case protoreflect.StringKind, protoreflect.BytesKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|2))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(len(", prefix, access, ")))")
		g.P("copy(dAtA[i:], ", prefix, access, ")")
		g.P("i += len(", prefix, access, ")")
	case protoreflect.MessageKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|2))")
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", access, ".Size()))")
		g.P(access, ".MarshalTo(dAtA[i:])")
		g.P("i += ", access, ".Size()")
	}

	if isPtr {
		g.P("}")
	}
}

func genScalarMarshal(g *protogen.GeneratedFile, v string, field *protogen.Field) {
	switch field.Desc.Kind() {
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.BoolKind, protoreflect.EnumKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", v, "))")
	case protoreflect.Sint32Kind, protoreflect.Sint64Kind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], protowire.EncodeZigZag(int64(", v, ")))")
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind:
		g.P("i += protowire.EncodeFixed32(dAtA[i:], uint32(", v, "))")
	case protoreflect.FloatKind:
		g.P("i += protowire.EncodeFixed32(dAtA[i:], math.Float32bits(", v, "))")
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind:
		g.P("i += protowire.EncodeFixed64(dAtA[i:], uint64(", v, "))")
	case protoreflect.DoubleKind:
		g.P("i += protowire.EncodeFixed64(dAtA[i:], math.Float64bits(", v, "))")
	}
}

func genMapKeyMarshal(g *protogen.GeneratedFile, k string, field *protogen.Field, fn int) {
	kf := field.Message.Fields[0]
	g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|", wireOf(kf), "))")
	switch kf.Desc.Kind() {
	case protoreflect.StringKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(len(", k, ")))")
		g.P("copy(dAtA[i:], ", k, ")")
		g.P("i += len(", k, ")")
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.BoolKind, protoreflect.EnumKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", k, "))")
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind:
		g.P("i += protowire.EncodeFixed32(dAtA[i:], uint32(", k, "))")
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind:
		g.P("i += protowire.EncodeFixed64(dAtA[i:], uint64(", k, "))")
	}
}

func genMapValMarshal(g *protogen.GeneratedFile, v string, field *protogen.Field, fn int) {
	vf := field.Message.Fields[1]
	g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", fn, "<<3|", wireOf(vf), "))")
	switch vf.Desc.Kind() {
	case protoreflect.StringKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(len(", v, ")))")
		g.P("copy(dAtA[i:], ", v, ")")
		g.P("i += len(", v, ")")
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind,
		protoreflect.BoolKind, protoreflect.EnumKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", v, "))")
	case protoreflect.Fixed32Kind, protoreflect.Sfixed32Kind, protoreflect.FloatKind:
		if vf.Desc.Kind() == protoreflect.FloatKind {
			g.P("i += protowire.EncodeFixed32(dAtA[i:], math.Float32bits(", v, "))")
		} else {
			g.P("i += protowire.EncodeFixed32(dAtA[i:], uint32(", v, "))")
		}
	case protoreflect.Fixed64Kind, protoreflect.Sfixed64Kind, protoreflect.DoubleKind:
		if vf.Desc.Kind() == protoreflect.DoubleKind {
			g.P("i += protowire.EncodeFixed64(dAtA[i:], math.Float64bits(", v, "))")
		} else {
			g.P("i += protowire.EncodeFixed64(dAtA[i:], uint64(", v, "))")
		}
	case protoreflect.MessageKind:
		g.P("i += protowire.EncodeVarint(dAtA[i:], uint64(", v, ".Size()))")
		g.P(v, ".MarshalTo(dAtA[i:])")
		g.P("i += ", v, ".Size()")
	}
}

// ---------------------------------------------------------------------------
// Unmarshal
// ---------------------------------------------------------------------------

func genUnmarshal(g *protogen.GeneratedFile, msg *protogen.Message) {
	g.P("func Unmarshal", msg.GoIdent.GoName, "(data []byte, ar *arena.Arena) (*", msg.GoIdent.GoName, ", error) {")
	g.P("m := arena.New[", msg.GoIdent.GoName, "](ar)")
	g.P("i := 0")
	g.P("for i < len(data) {")
	g.P("tag, n, err := protowire.DecodeVarint(data[i:])")
	g.P("if err != nil { return nil, err }")
	g.P("i += n")
	g.P("fieldNum := int(tag >> 3)")
	g.P("wireType := int(tag & 7)")
	g.P("switch fieldNum {")
	for _, field := range msg.Fields {
		genFieldUnmarshalCase(g, msg, field)
	}
	g.P("default:")
	g.P("skipped, err := protowire.SkipField(data[i:], wireType)")
	g.P("if err != nil { return nil, err }")
	g.P("i += skipped")
	g.P("}")
	g.P("}")
	for _, field := range msg.Fields {
		if field.Desc.Cardinality() == protoreflect.Required {
			g.P("if m.", field.GoName, " == nil { return nil, fmt.Errorf(\"proto: required field '", field.Desc.Name(), "' not set\") }")
		}
	}
	g.P("return m, nil")
	g.P("}")
	g.P()
}

func genFieldUnmarshalCase(g *protogen.GeneratedFile, msg *protogen.Message, field *protogen.Field) {
	desc := field.Desc
	fn := int(desc.Number())
	goName := field.GoName
	kind := desc.Kind()
	msgName := msg.GoIdent.GoName

	g.P("case ", fn, ":")

	if desc.IsMap() {
		genMapUnmarshal(g, field)
		return
	}

	if desc.IsList() {
		genRepeatedUnmarshal(g, field)
		return
	}

	isPtr := desc.HasOptionalKeyword() || desc.Cardinality() == protoreflect.Required
	isOneof := field.Oneof != nil

	switch kind {
	case protoreflect.Int32Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "int32(val)")
		} else {
			marshalAssign(g, goName, "int32(val)", isPtr)
		}
	case protoreflect.Int64Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "int64(val)")
		} else {
			marshalAssign(g, goName, "int64(val)", isPtr)
		}
	case protoreflect.Uint32Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "uint32(val)")
		} else {
			marshalAssign(g, goName, "uint32(val)", isPtr)
		}
	case protoreflect.Uint64Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "uint64(val)")
		} else {
			marshalAssign(g, goName, "uint64(val)", isPtr)
		}
	case protoreflect.Sint32Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "int32(protowire.DecodeZigZag(val))")
		} else {
			marshalAssign(g, goName, "int32(protowire.DecodeZigZag(val))", isPtr)
		}
	case protoreflect.Sint64Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "protowire.DecodeZigZag(val)")
		} else {
			marshalAssign(g, goName, "protowire.DecodeZigZag(val)", isPtr)
		}
	case protoreflect.BoolKind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "val != 0")
		} else {
			marshalAssign(g, goName, "val != 0", isPtr)
		}
	case protoreflect.EnumKind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		enumCast := string(field.Enum.GoIdent.GoName) + "(val)"
		if isOneof {
			genOneofAssign(g, msgName, field, enumCast)
		} else {
			marshalAssign(g, goName, enumCast, isPtr)
		}
	case protoreflect.Fixed32Kind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "val")
		} else {
			marshalAssign(g, goName, "val", isPtr)
		}
	case protoreflect.Sfixed32Kind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "int32(val)")
		} else {
			marshalAssign(g, goName, "int32(val)", isPtr)
		}
	case protoreflect.FloatKind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "math.Float32frombits(val)")
		} else {
			marshalAssign(g, goName, "math.Float32frombits(val)", isPtr)
		}
	case protoreflect.Fixed64Kind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "val")
		} else {
			marshalAssign(g, goName, "val", isPtr)
		}
	case protoreflect.Sfixed64Kind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "int64(val)")
		} else {
			marshalAssign(g, goName, "int64(val)", isPtr)
		}
	case protoreflect.DoubleKind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			genOneofAssign(g, msgName, field, "math.Float64frombits(val)")
		} else {
			marshalAssign(g, goName, "math.Float64frombits(val)", isPtr)
		}
	case protoreflect.StringKind:
		g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			wrapperName := msgName + "_" + goName
			g.P("w := arena.New[", wrapperName, "](ar)")
			g.P("w.Value = protowire.String(ar, data[i:i+int(length)])")
			g.P("m.", field.Oneof.GoName, " = w")
		} else if isPtr {
			g.P("m.", goName, " = protowire.StringPtr(ar, data[i:i+int(length)])")
		} else {
			g.P("m.", goName, " = protowire.String(ar, data[i:i+int(length)])")
		}
		g.P("i += int(length)")
	case protoreflect.BytesKind:
		g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		if isOneof {
			wrapperName := msgName + "_" + goName
			g.P("w := arena.New[", wrapperName, "](ar)")
			g.P("w.Value = ar.Bytes(data[i:i+int(length)])")
			g.P("m.", field.Oneof.GoName, " = w")
		} else if isPtr {
			g.P("m.", goName, " = protowire.Ptr(ar, ar.Bytes(data[i:i+int(length)]))")
		} else {
			g.P("m.", goName, " = ar.Bytes(data[i:i+int(length)])")
		}
		g.P("i += int(length)")
	case protoreflect.MessageKind:
		g.P("msgLen, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P("msg, err := Unmarshal", field.Message.GoIdent.GoName, "(data[i:i+int(msgLen)], ar)")
		g.P("if err != nil { return nil, err }")
		if isOneof {
			wrapperName := msgName + "_" + goName
			g.P("w := arena.New[", wrapperName, "](ar)")
			g.P("w.Value = msg")
			g.P("m.", field.Oneof.GoName, " = w")
		} else {
			g.P("m.", goName, " = msg")
		}
		g.P("i += int(msgLen)")
	}
}

func genOneofAssign(g *protogen.GeneratedFile, msgName string, field *protogen.Field, valExpr string) {
	wrapperName := msgName + "_" + field.GoName
	g.P("w := arena.New[", wrapperName, "](ar)")
	g.P("w.Value = ", valExpr)
	g.P("m.", field.Oneof.GoName, " = w")
}

func marshalAssign(g *protogen.GeneratedFile, goName, valExpr string, isPtr bool) {
	if isPtr {
		g.P("m.", goName, " = protowire.Ptr(ar, ", valExpr, ")")
	} else {
		g.P("m.", goName, " = ", valExpr)
	}
}

func genMapUnmarshal(g *protogen.GeneratedFile, field *protogen.Field) {
	goName := field.GoName
	kf := field.Message.Fields[0]
	vf := field.Message.Fields[1]
	keyType := elemType(kf)
	valType := elemType(vf)

	g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
	g.P("end := i + int(length)")
	g.P("var mk ", keyType)
	g.P("var mv ", valType)
	g.P("for i < end {")
	g.P("tag, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
	g.P("fieldNum := int(tag >> 3)")
	g.P("switch fieldNum {")
	g.P("case 1:")
	genMapFieldDecode(g, kf, "mk")
	g.P("case 2:")
	genMapFieldDecode(g, vf, "mv")
	g.P("default:")
	g.P("skipped, err := protowire.SkipField(data[i:], int(tag&7)); if err != nil { return nil, err }; i += skipped")
	g.P("}")
	g.P("}")
	g.P("if m.", goName, " == nil { m.", goName, " = arena.NewMap[", keyType, ", ", valType, "](ar, 0) }")
	g.P("m.", goName, ".Put(mk, mv)")
}

func genMapFieldDecode(g *protogen.GeneratedFile, field *protogen.Field, target string) {
	kind := field.Desc.Kind()
	switch kind {
	case protoreflect.Int32Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = int32(val)")
	case protoreflect.Int64Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = int64(val)")
	case protoreflect.Uint32Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = uint32(val)")
	case protoreflect.Uint64Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = uint64(val)")
	case protoreflect.Sint32Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = int32(protowire.DecodeZigZag(val))")
	case protoreflect.Sint64Kind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = protowire.DecodeZigZag(val)")
	case protoreflect.BoolKind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = val != 0")
	case protoreflect.StringKind:
		g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = protowire.String(ar, data[i:i+int(length)])")
		g.P("i += int(length)")
	case protoreflect.Fixed32Kind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = val")
	case protoreflect.Sfixed32Kind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = int32(val)")
	case protoreflect.FloatKind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = math.Float32frombits(val)")
	case protoreflect.Fixed64Kind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = val")
	case protoreflect.Sfixed64Kind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = int64(val)")
	case protoreflect.DoubleKind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = math.Float64frombits(val)")
	case protoreflect.MessageKind:
		g.P("msgLen, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P("msg, err := Unmarshal", field.Message.GoIdent.GoName, "(data[i:i+int(msgLen)], ar)")
		g.P("if err != nil { return nil, err }")
		g.P(target, " = msg")
		g.P("i += int(msgLen)")
	case protoreflect.EnumKind:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P(target, " = ", string(field.Enum.GoIdent.GoName), "(val)")
	}
}

func genRepeatedUnmarshal(g *protogen.GeneratedFile, field *protogen.Field) {
	goName := field.GoName
	kind := field.Desc.Kind()

	if isScalar(field) {
		g.P("if wireType == 2 {")
		g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P("end := i + int(length)")
		g.P("for i < end {")
		genScalarDecode(g, field)
		g.P("m.", goName, " = arena.Append(ar, m.", goName, ", ", castVal(field), ")")
		g.P("}")
		g.P("} else {")
		genScalarDecode(g, field)
		g.P("m.", goName, " = arena.Append(ar, m.", goName, ", ", castVal(field), ")")
		g.P("}")
	} else if kind == protoreflect.StringKind {
		g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P("m.", goName, " = arena.Append(ar, m.", goName, ", protowire.String(ar, data[i:i+int(length)]))")
		g.P("i += int(length)")
	} else if kind == protoreflect.BytesKind {
		g.P("length, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P("m.", goName, " = arena.Append(ar, m.", goName, ", ar.Bytes(data[i:i+int(length)]))")
		g.P("i += int(length)")
	} else if kind == protoreflect.MessageKind {
		g.P("msgLen, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
		g.P("msg, err := Unmarshal", field.Message.GoIdent.GoName, "(data[i:i+int(msgLen)], ar)")
		g.P("if err != nil { return nil, err }")
		g.P("m.", goName, " = arena.Append(ar, m.", goName, ", msg)")
		g.P("i += int(msgLen)")
	}
}

func genScalarDecode(g *protogen.GeneratedFile, field *protogen.Field) {
	kind := field.Desc.Kind()
	switch {
	case kind == protoreflect.Fixed32Kind || kind == protoreflect.Sfixed32Kind || kind == protoreflect.FloatKind:
		g.P("val, n, err := protowire.DecodeFixed32(data[i:]); if err != nil { return nil, err }; i += n")
	case kind == protoreflect.Fixed64Kind || kind == protoreflect.Sfixed64Kind || kind == protoreflect.DoubleKind:
		g.P("val, n, err := protowire.DecodeFixed64(data[i:]); if err != nil { return nil, err }; i += n")
	default:
		g.P("val, n, err := protowire.DecodeVarint(data[i:]); if err != nil { return nil, err }; i += n")
	}
}

func castVal(field *protogen.Field) string {
	kind := field.Desc.Kind()
	switch kind {
	case protoreflect.Int32Kind:
		return "int32(val)"
	case protoreflect.Int64Kind:
		return "int64(val)"
	case protoreflect.Uint32Kind:
		return "uint32(val)"
	case protoreflect.Uint64Kind:
		return "uint64(val)"
	case protoreflect.Sint32Kind:
		return "int32(protowire.DecodeZigZag(val))"
	case protoreflect.Sint64Kind:
		return "protowire.DecodeZigZag(val)"
	case protoreflect.BoolKind:
		return "val != 0"
	case protoreflect.EnumKind:
		return string(field.Enum.GoIdent.GoName) + "(val)"
	case protoreflect.FloatKind:
		return "math.Float32frombits(val)"
	case protoreflect.DoubleKind:
		return "math.Float64frombits(val)"
	case protoreflect.Sfixed32Kind:
		return "int32(val)"
	case protoreflect.Sfixed64Kind:
		return "int64(val)"
	default:
		return "val"
	}
}
