// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test.proto

package arenatest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum types
type Role int32

const (
	Role_UNKNOWN Role = 0
	Role_ADMIN   Role = 1
	Role_USER    Role = 2
	Role_GUEST   Role = -1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "ADMIN",
		2:  "USER",
		-1: "GUEST",
	}
	Role_value = map[string]int32{
		"UNKNOWN": 0,
		"ADMIN":   1,
		"USER":    2,
		"GUEST":   -1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Role) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Role(num)
	return nil
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

// All scalar field types
type Scalars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptInt32      *int32                 `protobuf:"varint,1,opt,name=opt_int32,json=optInt32" json:"opt_int32,omitempty"`
	OptInt64      *int64                 `protobuf:"varint,2,opt,name=opt_int64,json=optInt64" json:"opt_int64,omitempty"`
	OptUint32     *uint32                `protobuf:"varint,3,opt,name=opt_uint32,json=optUint32" json:"opt_uint32,omitempty"`
	OptUint64     *uint64                `protobuf:"varint,4,opt,name=opt_uint64,json=optUint64" json:"opt_uint64,omitempty"`
	OptSint32     *int32                 `protobuf:"zigzag32,5,opt,name=opt_sint32,json=optSint32" json:"opt_sint32,omitempty"`
	OptSint64     *int64                 `protobuf:"zigzag64,6,opt,name=opt_sint64,json=optSint64" json:"opt_sint64,omitempty"`
	OptFixed32    *uint32                `protobuf:"fixed32,7,opt,name=opt_fixed32,json=optFixed32" json:"opt_fixed32,omitempty"`
	OptFixed64    *uint64                `protobuf:"fixed64,8,opt,name=opt_fixed64,json=optFixed64" json:"opt_fixed64,omitempty"`
	OptSfixed32   *int32                 `protobuf:"fixed32,9,opt,name=opt_sfixed32,json=optSfixed32" json:"opt_sfixed32,omitempty"`
	OptSfixed64   *int64                 `protobuf:"fixed64,10,opt,name=opt_sfixed64,json=optSfixed64" json:"opt_sfixed64,omitempty"`
	OptFloat      *float32               `protobuf:"fixed32,11,opt,name=opt_float,json=optFloat" json:"opt_float,omitempty"`
	OptDouble     *float64               `protobuf:"fixed64,12,opt,name=opt_double,json=optDouble" json:"opt_double,omitempty"`
	OptBool       *bool                  `protobuf:"varint,13,opt,name=opt_bool,json=optBool" json:"opt_bool,omitempty"`
	OptString     *string                `protobuf:"bytes,14,opt,name=opt_string,json=optString" json:"opt_string,omitempty"`
	OptBytes      []byte                 `protobuf:"bytes,15,opt,name=opt_bytes,json=optBytes" json:"opt_bytes,omitempty"`
	OptEnum       *Role                  `protobuf:"varint,16,opt,name=opt_enum,json=optEnum,enum=test.Role" json:"opt_enum,omitempty"`
	ReqString     *string                `protobuf:"bytes,20,req,name=req_string,json=reqString" json:"req_string,omitempty"`
	ReqInt32      *int32                 `protobuf:"varint,21,req,name=req_int32,json=reqInt32" json:"req_int32,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalars) Reset() {
	*x = Scalars{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalars) ProtoMessage() {}

func (x *Scalars) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalars.ProtoReflect.Descriptor instead.
func (*Scalars) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Scalars) GetOptInt32() int32 {
	if x != nil && x.OptInt32 != nil {
		return *x.OptInt32
	}
	return 0
}

func (x *Scalars) GetOptInt64() int64 {
	if x != nil && x.OptInt64 != nil {
		return *x.OptInt64
	}
	return 0
}

func (x *Scalars) GetOptUint32() uint32 {
	if x != nil && x.OptUint32 != nil {
		return *x.OptUint32
	}
	return 0
}

func (x *Scalars) GetOptUint64() uint64 {
	if x != nil && x.OptUint64 != nil {
		return *x.OptUint64
	}
	return 0
}

func (x *Scalars) GetOptSint32() int32 {
	if x != nil && x.OptSint32 != nil {
		return *x.OptSint32
	}
	return 0
}

func (x *Scalars) GetOptSint64() int64 {
	if x != nil && x.OptSint64 != nil {
		return *x.OptSint64
	}
	return 0
}

func (x *Scalars) GetOptFixed32() uint32 {
	if x != nil && x.OptFixed32 != nil {
		return *x.OptFixed32
	}
	return 0
}

func (x *Scalars) GetOptFixed64() uint64 {
	if x != nil && x.OptFixed64 != nil {
		return *x.OptFixed64
	}
	return 0
}

func (x *Scalars) GetOptSfixed32() int32 {
	if x != nil && x.OptSfixed32 != nil {
		return *x.OptSfixed32
	}
	return 0
}

func (x *Scalars) GetOptSfixed64() int64 {
	if x != nil && x.OptSfixed64 != nil {
		return *x.OptSfixed64
	}
	return 0
}

func (x *Scalars) GetOptFloat() float32 {
	if x != nil && x.OptFloat != nil {
		return *x.OptFloat
	}
	return 0
}

func (x *Scalars) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return 0
}

func (x *Scalars) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *Scalars) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

func (x *Scalars) GetOptBytes() []byte {
	if x != nil {
		return x.OptBytes
	}
	return nil
}

func (x *Scalars) GetOptEnum() Role {
	if x != nil && x.OptEnum != nil {
		return *x.OptEnum
	}
	return Role_UNKNOWN
}

func (x *Scalars) GetReqString() string {
	if x != nil && x.ReqString != nil {
		return *x.ReqString
	}
	return ""
}

func (x *Scalars) GetReqInt32() int32 {
	if x != nil && x.ReqInt32 != nil {
		return *x.ReqInt32
	}
	return 0
}

type Defaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithDefault   *int32                 `protobuf:"varint,1,opt,name=with_default,json=withDefault,def=42" json:"with_default,omitempty"`
	StrDefault    *string                `protobuf:"bytes,2,opt,name=str_default,json=strDefault,def=hello" json:"str_default,omitempty"`
	BoolDefault   *bool                  `protobuf:"varint,3,opt,name=bool_default,json=boolDefault,def=1" json:"bool_default,omitempty"`
	EnumDefault   *Role                  `protobuf:"varint,4,opt,name=enum_default,json=enumDefault,enum=test.Role,def=1" json:"enum_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for Defaults fields.
const (
	Default_Defaults_WithDefault = int32(42)
	Default_Defaults_StrDefault  = string("hello")
	Default_Defaults_BoolDefault = bool(true)
	Default_Defaults_EnumDefault = Role_ADMIN
)

func (x *Defaults) Reset() {
	*x = Defaults{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Defaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Defaults) ProtoMessage() {}

func (x *Defaults) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Defaults.ProtoReflect.Descriptor instead.
func (*Defaults) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *Defaults) GetWithDefault() int32 {
	if x != nil && x.WithDefault != nil {
		return *x.WithDefault
	}
	return Default_Defaults_WithDefault
}

func (x *Defaults) GetStrDefault() string {
	if x != nil && x.StrDefault != nil {
		return *x.StrDefault
	}
	return Default_Defaults_StrDefault
}

func (x *Defaults) GetBoolDefault() bool {
	if x != nil && x.BoolDefault != nil {
		return *x.BoolDefault
	}
	return Default_Defaults_BoolDefault
}

func (x *Defaults) GetEnumDefault() Role {
	if x != nil && x.EnumDefault != nil {
		return *x.EnumDefault
	}
	return Default_Defaults_EnumDefault
}

// Repeated fields
type Repeated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnpackedInt32 []int32                `protobuf:"varint,1,rep,name=unpacked_int32,json=unpackedInt32" json:"unpacked_int32,omitempty"`
	Strings       []string               `protobuf:"bytes,2,rep,name=strings" json:"strings,omitempty"`
	PackedInt32   []int32                `protobuf:"varint,3,rep,packed,name=packed_int32,json=packedInt32" json:"packed_int32,omitempty"`
	PackedEnum    []Role                 `protobuf:"varint,4,rep,packed,name=packed_enum,json=packedEnum,enum=test.Role" json:"packed_enum,omitempty"`
	Doubles       []float64              `protobuf:"fixed64,5,rep,packed,name=doubles" json:"doubles,omitempty"`
	ByteSlices    [][]byte               `protobuf:"bytes,6,rep,name=byte_slices,json=byteSlices" json:"byte_slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repeated) Reset() {
	*x = Repeated{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repeated) ProtoMessage() {}

func (x *Repeated) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repeated.ProtoReflect.Descriptor instead.
func (*Repeated) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *Repeated) GetUnpackedInt32() []int32 {
	if x != nil {
		return x.UnpackedInt32
	}
	return nil
}

func (x *Repeated) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Repeated) GetPackedInt32() []int32 {
	if x != nil {
		return x.PackedInt32
	}
	return nil
}

func (x *Repeated) GetPackedEnum() []Role {
	if x != nil {
		return x.PackedEnum
	}
	return nil
}

func (x *Repeated) GetDoubles() []float64 {
	if x != nil {
		return x.Doubles
	}
	return nil
}

func (x *Repeated) GetByteSlices() [][]byte {
	if x != nil {
		return x.ByteSlices
	}
	return nil
}

// Nested messages
type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *Inner) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Inner) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Middle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inner         *Inner                 `protobuf:"bytes,1,opt,name=inner" json:"inner,omitempty"`
	Label         *string                `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Middle) Reset() {
	*x = Middle{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Middle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Middle) ProtoMessage() {}

func (x *Middle) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Middle.ProtoReflect.Descriptor instead.
func (*Middle) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *Middle) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Middle) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

type Outer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middle        *Middle                `protobuf:"bytes,1,opt,name=middle" json:"middle,omitempty"`
	Tag           *string                `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *Outer) GetMiddle() *Middle {
	if x != nil {
		return x.Middle
	}
	return nil
}

func (x *Outer) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

// Map fields
type Maps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringInt32   map[string]int32       `protobuf:"bytes,1,rep,name=string_int32,json=stringInt32" json:"string_int32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringString  map[string]string      `protobuf:"bytes,2,rep,name=string_string,json=stringString" json:"string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Int32Msg      map[int32]*Inner       `protobuf:"bytes,3,rep,name=int32_msg,json=int32Msg" json:"int32_msg,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maps) Reset() {
	*x = Maps{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maps) ProtoMessage() {}

func (x *Maps) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maps.ProtoReflect.Descriptor instead.
func (*Maps) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *Maps) GetStringInt32() map[string]int32 {
	if x != nil {
		return x.StringInt32
	}
	return nil
}

func (x *Maps) GetStringString() map[string]string {
	if x != nil {
		return x.StringString
	}
	return nil
}

func (x *Maps) GetInt32Msg() map[int32]*Inner {
	if x != nil {
		return x.Int32Msg
	}
	return nil
}

// Oneof
type OneofMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*OneofMsg_StrVal
	//	*OneofMsg_BytesVal
	//	*OneofMsg_MsgVal
	//	*OneofMsg_IntVal
	Choice        isOneofMsg_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofMsg) Reset() {
	*x = OneofMsg{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofMsg) ProtoMessage() {}

func (x *OneofMsg) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofMsg.ProtoReflect.Descriptor instead.
func (*OneofMsg) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *OneofMsg) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OneofMsg) GetChoice() isOneofMsg_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *OneofMsg) GetStrVal() string {
	if x != nil {
		if x, ok := x.Choice.(*OneofMsg_StrVal); ok {
			return x.StrVal
		}
	}
	return ""
}

func (x *OneofMsg) GetBytesVal() []byte {
	if x != nil {
		if x, ok := x.Choice.(*OneofMsg_BytesVal); ok {
			return x.BytesVal
		}
	}
	return nil
}

func (x *OneofMsg) GetMsgVal() *Inner {
	if x != nil {
		if x, ok := x.Choice.(*OneofMsg_MsgVal); ok {
			return x.MsgVal
		}
	}
	return nil
}

func (x *OneofMsg) GetIntVal() int32 {
	if x != nil {
		if x, ok := x.Choice.(*OneofMsg_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

type isOneofMsg_Choice interface {
	isOneofMsg_Choice()
}

type OneofMsg_StrVal struct {
	StrVal string `protobuf:"bytes,2,opt,name=str_val,json=strVal,oneof"`
}

type OneofMsg_BytesVal struct {
	BytesVal []byte `protobuf:"bytes,3,opt,name=bytes_val,json=bytesVal,oneof"`
}

type OneofMsg_MsgVal struct {
	MsgVal *Inner `protobuf:"bytes,4,opt,name=msg_val,json=msgVal,oneof"`
}

type OneofMsg_IntVal struct {
	IntVal int32 `protobuf:"varint,5,opt,name=int_val,json=intVal,oneof"`
}

func (*OneofMsg_StrVal) isOneofMsg_Choice() {}

func (*OneofMsg_BytesVal) isOneofMsg_Choice() {}

func (*OneofMsg_MsgVal) isOneofMsg_Choice() {}

func (*OneofMsg_IntVal) isOneofMsg_Choice() {}

// Full-featured message for round-trip testing
type FullMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Label  *string                `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Tags   []string               `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
	Scores map[string]int32       `protobuf:"bytes,4,rep,name=scores" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Nested *Inner                 `protobuf:"bytes,5,opt,name=nested" json:"nested,omitempty"`
	Role   *Role                  `protobuf:"varint,6,opt,name=role,enum=test.Role" json:"role,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FullMessage_TextPayload
	//	*FullMessage_BinaryPayload
	Payload       isFullMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullMessage) Reset() {
	*x = FullMessage{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullMessage) ProtoMessage() {}

func (x *FullMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullMessage.ProtoReflect.Descriptor instead.
func (*FullMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *FullMessage) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *FullMessage) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *FullMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FullMessage) GetScores() map[string]int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *FullMessage) GetNested() *Inner {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *FullMessage) GetRole() Role {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return Role_UNKNOWN
}

func (x *FullMessage) GetPayload() isFullMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FullMessage) GetTextPayload() string {
	if x != nil {
		if x, ok := x.Payload.(*FullMessage_TextPayload); ok {
			return x.TextPayload
		}
	}
	return ""
}

func (x *FullMessage) GetBinaryPayload() []byte {
	if x != nil {
		if x, ok := x.Payload.(*FullMessage_BinaryPayload); ok {
			return x.BinaryPayload
		}
	}
	return nil
}

type isFullMessage_Payload interface {
	isFullMessage_Payload()
}

type FullMessage_TextPayload struct {
	TextPayload string `protobuf:"bytes,7,opt,name=text_payload,json=textPayload,oneof"`
}

type FullMessage_BinaryPayload struct {
	BinaryPayload []byte `protobuf:"bytes,8,opt,name=binary_payload,json=binaryPayload,oneof"`
}

func (*FullMessage_TextPayload) isFullMessage_Payload() {}

func (*FullMessage_BinaryPayload) isFullMessage_Payload() {}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x04test\"\xbd\x04\n" +
	"\aScalars\x12\x1b\n" +
	"\topt_int32\x18\x01 \x01(\x05R\boptInt32\x12\x1b\n" +
	"\topt_int64\x18\x02 \x01(\x03R\boptInt64\x12\x1d\n" +
	"\n" +
	"opt_uint32\x18\x03 \x01(\rR\toptUint32\x12\x1d\n" +
	"\n" +
	"opt_uint64\x18\x04 \x01(\x04R\toptUint64\x12\x1d\n" +
	"\n" +
	"opt_sint32\x18\x05 \x01(\x11R\toptSint32\x12\x1d\n" +
	"\n" +
	"opt_sint64\x18\x06 \x01(\x12R\toptSint64\x12\x1f\n" +
	"\vopt_fixed32\x18\a \x01(\aR\n" +
	"optFixed32\x12\x1f\n" +
	"\vopt_fixed64\x18\b \x01(\x06R\n" +
	"optFixed64\x12!\n" +
	"\fopt_sfixed32\x18\t \x01(\x0fR\voptSfixed32\x12!\n" +
	"\fopt_sfixed64\x18\n" +
	" \x01(\x10R\voptSfixed64\x12\x1b\n" +
	"\topt_float\x18\v \x01(\x02R\boptFloat\x12\x1d\n" +
	"\n" +
	"opt_double\x18\f \x01(\x01R\toptDouble\x12\x19\n" +
	"\bopt_bool\x18\r \x01(\bR\aoptBool\x12\x1d\n" +
	"\n" +
	"opt_string\x18\x0e \x01(\tR\toptString\x12\x1b\n" +
	"\topt_bytes\x18\x0f \x01(\fR\boptBytes\x12%\n" +
	"\bopt_enum\x18\x10 \x01(\x0e2\n" +
	".test.RoleR\aoptEnum\x12\x1d\n" +
	"\n" +
	"req_string\x18\x14 \x02(\tR\treqString\x12\x1b\n" +
	"\treq_int32\x18\x15 \x02(\x05R\breqInt32\"\xb8\x01\n" +
	"\bDefaults\x12%\n" +
	"\fwith_default\x18\x01 \x01(\x05:\x0242R\vwithDefault\x12&\n" +
	"\vstr_default\x18\x02 \x01(\t:\x05helloR\n" +
	"strDefault\x12'\n" +
	"\fbool_default\x18\x03 \x01(\b:\x04trueR\vboolDefault\x124\n" +
	"\fenum_default\x18\x04 \x01(\x0e2\n" +
	".test.Role:\x05ADMINR\venumDefault\"\xe2\x01\n" +
	"\bRepeated\x12%\n" +
	"\x0eunpacked_int32\x18\x01 \x03(\x05R\runpackedInt32\x12\x18\n" +
	"\astrings\x18\x02 \x03(\tR\astrings\x12%\n" +
	"\fpacked_int32\x18\x03 \x03(\x05B\x02\x10\x01R\vpackedInt32\x12/\n" +
	"\vpacked_enum\x18\x04 \x03(\x0e2\n" +
	".test.RoleB\x02\x10\x01R\n" +
	"packedEnum\x12\x1c\n" +
	"\adoubles\x18\x05 \x03(\x01B\x02\x10\x01R\adoubles\x12\x1f\n" +
	"\vbyte_slices\x18\x06 \x03(\fR\n" +
	"byteSlices\"1\n" +
	"\x05Inner\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"A\n" +
	"\x06Middle\x12!\n" +
	"\x05inner\x18\x01 \x01(\v2\v.test.InnerR\x05inner\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"?\n" +
	"\x05Outer\x12$\n" +
	"\x06middle\x18\x01 \x01(\v2\f.test.MiddleR\x06middle\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"\x8b\x03\n" +
	"\x04Maps\x12>\n" +
	"\fstring_int32\x18\x01 \x03(\v2\x1b.test.Maps.StringInt32EntryR\vstringInt32\x12A\n" +
	"\rstring_string\x18\x02 \x03(\v2\x1c.test.Maps.StringStringEntryR\fstringString\x125\n" +
	"\tint32_msg\x18\x03 \x03(\v2\x18.test.Maps.Int32MsgEntryR\bint32Msg\x1a>\n" +
	"\x10StringInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11StringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\rInt32MsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.test.InnerR\x05value:\x028\x01\"\xa5\x01\n" +
	"\bOneofMsg\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\astr_val\x18\x02 \x01(\tH\x00R\x06strVal\x12\x1d\n" +
	"\tbytes_val\x18\x03 \x01(\fH\x00R\bbytesVal\x12&\n" +
	"\amsg_val\x18\x04 \x01(\v2\v.test.InnerH\x00R\x06msgVal\x12\x19\n" +
	"\aint_val\x18\x05 \x01(\x05H\x00R\x06intValB\b\n" +
	"\x06choice\"\xd7\x02\n" +
	"\vFullMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x125\n" +
	"\x06scores\x18\x04 \x03(\v2\x1d.test.FullMessage.ScoresEntryR\x06scores\x12#\n" +
	"\x06nested\x18\x05 \x01(\v2\v.test.InnerR\x06nested\x12\x1e\n" +
	"\x04role\x18\x06 \x01(\x0e2\n" +
	".test.RoleR\x04role\x12#\n" +
	"\ftext_payload\x18\a \x01(\tH\x00R\vtextPayload\x12'\n" +
	"\x0ebinary_payload\x18\b \x01(\fH\x00R\rbinaryPayload\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B\t\n" +
	"\apayload*<\n" +
	"\x04Role\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\b\n" +
	"\x04USER\x10\x02\x12\x12\n" +
	"\x05GUEST\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01BDZBgithub.com/limpo1989/arena/cmd/protoc-gen-arena/testdata/arenatest"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_test_proto_goTypes = []any{
	(Role)(0),           // 0: test.Role
	(*Scalars)(nil),     // 1: test.Scalars
	(*Defaults)(nil),    // 2: test.Defaults
	(*Repeated)(nil),    // 3: test.Repeated
	(*Inner)(nil),       // 4: test.Inner
	(*Middle)(nil),      // 5: test.Middle
	(*Outer)(nil),       // 6: test.Outer
	(*Maps)(nil),        // 7: test.Maps
	(*OneofMsg)(nil),    // 8: test.OneofMsg
	(*FullMessage)(nil), // 9: test.FullMessage
	nil,                 // 10: test.Maps.StringInt32Entry
	nil,                 // 11: test.Maps.StringStringEntry
	nil,                 // 12: test.Maps.Int32MsgEntry
	nil,                 // 13: test.FullMessage.ScoresEntry
}
var file_test_proto_depIdxs = []int32{
	0,  // 0: test.Scalars.opt_enum:type_name -> test.Role
	0,  // 1: test.Defaults.enum_default:type_name -> test.Role
	0,  // 2: test.Repeated.packed_enum:type_name -> test.Role
	4,  // 3: test.Middle.inner:type_name -> test.Inner
	5,  // 4: test.Outer.middle:type_name -> test.Middle
	10, // 5: test.Maps.string_int32:type_name -> test.Maps.StringInt32Entry
	11, // 6: test.Maps.string_string:type_name -> test.Maps.StringStringEntry
	12, // 7: test.Maps.int32_msg:type_name -> test.Maps.Int32MsgEntry
	4,  // 8: test.OneofMsg.msg_val:type_name -> test.Inner
	13, // 9: test.FullMessage.scores:type_name -> test.FullMessage.ScoresEntry
	4,  // 10: test.FullMessage.nested:type_name -> test.Inner
	0,  // 11: test.FullMessage.role:type_name -> test.Role
	4,  // 12: test.Maps.Int32MsgEntry.value:type_name -> test.Inner
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[7].OneofWrappers = []any{
		(*OneofMsg_StrVal)(nil),
		(*OneofMsg_BytesVal)(nil),
		(*OneofMsg_MsgVal)(nil),
		(*OneofMsg_IntVal)(nil),
	}
	file_test_proto_msgTypes[8].OneofWrappers = []any{
		(*FullMessage_TextPayload)(nil),
		(*FullMessage_BinaryPayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
