// Code generated by protoc-gen-arena. DO NOT EDIT.
// source: test.proto

package arenatest

import (
	"fmt"
	"github.com/limpo1989/arena"
	"github.com/limpo1989/arena/protowire"
	"math"
)

type Role int32

const (
	Role_UNKNOWN Role = 0
	Role_ADMIN   Role = 1
	Role_USER    Role = 2
	Role_GUEST   Role = -1
)

type Scalars struct {
	OptInt32    *int32
	OptInt64    *int64
	OptUint32   *uint32
	OptUint64   *uint64
	OptSint32   *int32
	OptSint64   *int64
	OptFixed32  *uint32
	OptFixed64  *uint64
	OptSfixed32 *int32
	OptSfixed64 *int64
	OptFloat    *float32
	OptDouble   *float64
	OptBool     *bool
	OptString   *string
	OptBytes    *[]byte
	OptEnum     *Role
	ReqString   *string
	ReqInt32    *int32
}

func (m *Scalars) GetOptInt32() int32 {
	if m != nil && m.OptInt32 != nil {
		return *m.OptInt32
	}
	return 0
}

func (m *Scalars) HasOptInt32() bool {
	return m != nil && m.OptInt32 != nil
}

func (m *Scalars) GetOptInt64() int64 {
	if m != nil && m.OptInt64 != nil {
		return *m.OptInt64
	}
	return 0
}

func (m *Scalars) HasOptInt64() bool {
	return m != nil && m.OptInt64 != nil
}

func (m *Scalars) GetOptUint32() uint32 {
	if m != nil && m.OptUint32 != nil {
		return *m.OptUint32
	}
	return 0
}

func (m *Scalars) HasOptUint32() bool {
	return m != nil && m.OptUint32 != nil
}

func (m *Scalars) GetOptUint64() uint64 {
	if m != nil && m.OptUint64 != nil {
		return *m.OptUint64
	}
	return 0
}

func (m *Scalars) HasOptUint64() bool {
	return m != nil && m.OptUint64 != nil
}

func (m *Scalars) GetOptSint32() int32 {
	if m != nil && m.OptSint32 != nil {
		return *m.OptSint32
	}
	return 0
}

func (m *Scalars) HasOptSint32() bool {
	return m != nil && m.OptSint32 != nil
}

func (m *Scalars) GetOptSint64() int64 {
	if m != nil && m.OptSint64 != nil {
		return *m.OptSint64
	}
	return 0
}

func (m *Scalars) HasOptSint64() bool {
	return m != nil && m.OptSint64 != nil
}

func (m *Scalars) GetOptFixed32() uint32 {
	if m != nil && m.OptFixed32 != nil {
		return *m.OptFixed32
	}
	return 0
}

func (m *Scalars) HasOptFixed32() bool {
	return m != nil && m.OptFixed32 != nil
}

func (m *Scalars) GetOptFixed64() uint64 {
	if m != nil && m.OptFixed64 != nil {
		return *m.OptFixed64
	}
	return 0
}

func (m *Scalars) HasOptFixed64() bool {
	return m != nil && m.OptFixed64 != nil
}

func (m *Scalars) GetOptSfixed32() int32 {
	if m != nil && m.OptSfixed32 != nil {
		return *m.OptSfixed32
	}
	return 0
}

func (m *Scalars) HasOptSfixed32() bool {
	return m != nil && m.OptSfixed32 != nil
}

func (m *Scalars) GetOptSfixed64() int64 {
	if m != nil && m.OptSfixed64 != nil {
		return *m.OptSfixed64
	}
	return 0
}

func (m *Scalars) HasOptSfixed64() bool {
	return m != nil && m.OptSfixed64 != nil
}

func (m *Scalars) GetOptFloat() float32 {
	if m != nil && m.OptFloat != nil {
		return *m.OptFloat
	}
	return 0
}

func (m *Scalars) HasOptFloat() bool {
	return m != nil && m.OptFloat != nil
}

func (m *Scalars) GetOptDouble() float64 {
	if m != nil && m.OptDouble != nil {
		return *m.OptDouble
	}
	return 0
}

func (m *Scalars) HasOptDouble() bool {
	return m != nil && m.OptDouble != nil
}

func (m *Scalars) GetOptBool() bool {
	if m != nil && m.OptBool != nil {
		return *m.OptBool
	}
	return false
}

func (m *Scalars) HasOptBool() bool {
	return m != nil && m.OptBool != nil
}

func (m *Scalars) GetOptString() string {
	if m != nil && m.OptString != nil {
		return *m.OptString
	}
	return ""
}

func (m *Scalars) HasOptString() bool {
	return m != nil && m.OptString != nil
}

func (m *Scalars) GetOptBytes() []byte {
	if m != nil && m.OptBytes != nil {
		return *m.OptBytes
	}
	return nil
}

func (m *Scalars) HasOptBytes() bool {
	return m != nil && m.OptBytes != nil
}

func (m *Scalars) GetOptEnum() Role {
	if m != nil && m.OptEnum != nil {
		return *m.OptEnum
	}
	return Role_UNKNOWN
}

func (m *Scalars) HasOptEnum() bool {
	return m != nil && m.OptEnum != nil
}

func (m *Scalars) GetReqString() string {
	if m != nil && m.ReqString != nil {
		return *m.ReqString
	}
	return ""
}

func (m *Scalars) GetReqInt32() int32 {
	if m != nil && m.ReqInt32 != nil {
		return *m.ReqInt32
	}
	return 0
}

func (m *Scalars) Size() (n int) {
	if m.OptInt32 != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|0)) + protowire.SizeOfVarint(uint64(*m.OptInt32))
	}
	if m.OptInt64 != nil {
		n += protowire.SizeOfVarint(uint64(2<<3|0)) + protowire.SizeOfVarint(uint64(*m.OptInt64))
	}
	if m.OptUint32 != nil {
		n += protowire.SizeOfVarint(uint64(3<<3|0)) + protowire.SizeOfVarint(uint64(*m.OptUint32))
	}
	if m.OptUint64 != nil {
		n += protowire.SizeOfVarint(uint64(4<<3|0)) + protowire.SizeOfVarint(uint64(*m.OptUint64))
	}
	if m.OptSint32 != nil {
		n += protowire.SizeOfVarint(uint64(5<<3|0)) + protowire.SizeOfVarint(protowire.EncodeZigZag(int64(*m.OptSint32)))
	}
	if m.OptSint64 != nil {
		n += protowire.SizeOfVarint(uint64(6<<3|0)) + protowire.SizeOfVarint(protowire.EncodeZigZag(int64(*m.OptSint64)))
	}
	if m.OptFixed32 != nil {
		n += protowire.SizeOfVarint(uint64(7<<3|5)) + 4
	}
	if m.OptFixed64 != nil {
		n += protowire.SizeOfVarint(uint64(8<<3|1)) + 8
	}
	if m.OptSfixed32 != nil {
		n += protowire.SizeOfVarint(uint64(9<<3|5)) + 4
	}
	if m.OptSfixed64 != nil {
		n += protowire.SizeOfVarint(uint64(10<<3|1)) + 8
	}
	if m.OptFloat != nil {
		n += protowire.SizeOfVarint(uint64(11<<3|5)) + 4
	}
	if m.OptDouble != nil {
		n += protowire.SizeOfVarint(uint64(12<<3|1)) + 8
	}
	if m.OptBool != nil {
		n += protowire.SizeOfVarint(uint64(13<<3|0)) + 1
	}
	if m.OptString != nil {
		n += protowire.SizeOfVarint(uint64(14<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.OptString))) + len(*m.OptString)
	}
	if m.OptBytes != nil {
		n += protowire.SizeOfVarint(uint64(15<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.OptBytes))) + len(*m.OptBytes)
	}
	if m.OptEnum != nil {
		n += protowire.SizeOfVarint(uint64(16<<3|0)) + protowire.SizeOfVarint(uint64(*m.OptEnum))
	}
	if m.ReqString != nil {
		n += protowire.SizeOfVarint(uint64(20<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.ReqString))) + len(*m.ReqString)
	}
	if m.ReqInt32 != nil {
		n += protowire.SizeOfVarint(uint64(21<<3|0)) + protowire.SizeOfVarint(uint64(*m.ReqInt32))
	}
	return
}

func (m *Scalars) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.OptInt32 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.OptInt32))
	}
	if m.OptInt64 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.OptInt64))
	}
	if m.OptUint32 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(3<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.OptUint32))
	}
	if m.OptUint64 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(4<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.OptUint64))
	}
	if m.OptSint32 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(5<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], protowire.EncodeZigZag(int64(*m.OptSint32)))
	}
	if m.OptSint64 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(6<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], protowire.EncodeZigZag(int64(*m.OptSint64)))
	}
	if m.OptFixed32 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(7<<3|5))
		i += protowire.EncodeFixed32(dAtA[i:], *m.OptFixed32)
	}
	if m.OptFixed64 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(8<<3|1))
		i += protowire.EncodeFixed64(dAtA[i:], *m.OptFixed64)
	}
	if m.OptSfixed32 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(9<<3|5))
		i += protowire.EncodeFixed32(dAtA[i:], uint32(*m.OptSfixed32))
	}
	if m.OptSfixed64 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(10<<3|1))
		i += protowire.EncodeFixed64(dAtA[i:], uint64(*m.OptSfixed64))
	}
	if m.OptFloat != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(11<<3|5))
		i += protowire.EncodeFixed32(dAtA[i:], math.Float32bits(*m.OptFloat))
	}
	if m.OptDouble != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(12<<3|1))
		i += protowire.EncodeFixed64(dAtA[i:], math.Float64bits(*m.OptDouble))
	}
	if m.OptBool != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(13<<3|0))
		if *m.OptBool {
			dAtA[i] = 1
			i++
		} else {
			dAtA[i] = 0
			i++
		}
	}
	if m.OptString != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(14<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.OptString)))
		copy(dAtA[i:], *m.OptString)
		i += len(*m.OptString)
	}
	if m.OptBytes != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(15<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.OptBytes)))
		copy(dAtA[i:], *m.OptBytes)
		i += len(*m.OptBytes)
	}
	if m.OptEnum != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(16<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.OptEnum))
	}
	if m.ReqString != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(20<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.ReqString)))
		copy(dAtA[i:], *m.ReqString)
		i += len(*m.ReqString)
	}
	if m.ReqInt32 != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(21<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.ReqInt32))
	}
	return i, nil
}

func (m *Scalars) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalScalars(data []byte, ar *arena.Arena) (*Scalars, error) {
	m := arena.New[Scalars](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptInt32 = protowire.Ptr(ar, int32(val))
		case 2:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptInt64 = protowire.Ptr(ar, int64(val))
		case 3:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptUint32 = protowire.Ptr(ar, uint32(val))
		case 4:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptUint64 = protowire.Ptr(ar, uint64(val))
		case 5:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptSint32 = protowire.Ptr(ar, int32(protowire.DecodeZigZag(val)))
		case 6:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptSint64 = protowire.Ptr(ar, protowire.DecodeZigZag(val))
		case 7:
			val, n, err := protowire.DecodeFixed32(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptFixed32 = protowire.Ptr(ar, val)
		case 8:
			val, n, err := protowire.DecodeFixed64(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptFixed64 = protowire.Ptr(ar, val)
		case 9:
			val, n, err := protowire.DecodeFixed32(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptSfixed32 = protowire.Ptr(ar, int32(val))
		case 10:
			val, n, err := protowire.DecodeFixed64(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptSfixed64 = protowire.Ptr(ar, int64(val))
		case 11:
			val, n, err := protowire.DecodeFixed32(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptFloat = protowire.Ptr(ar, math.Float32frombits(val))
		case 12:
			val, n, err := protowire.DecodeFixed64(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptDouble = protowire.Ptr(ar, math.Float64frombits(val))
		case 13:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptBool = protowire.Ptr(ar, val != 0)
		case 14:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptString = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		case 15:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptBytes = protowire.Ptr(ar, ar.Bytes(data[i:i+int(length)]))
			i += int(length)
		case 16:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.OptEnum = protowire.Ptr(ar, Role(val))
		case 20:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.ReqString = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		case 21:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.ReqInt32 = protowire.Ptr(ar, int32(val))
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	if m.ReqString == nil {
		return nil, fmt.Errorf("proto: required field 'req_string' not set")
	}
	if m.ReqInt32 == nil {
		return nil, fmt.Errorf("proto: required field 'req_int32' not set")
	}
	return m, nil
}

type Defaults struct {
	WithDefault *int32
	StrDefault  *string
	BoolDefault *bool
	EnumDefault *Role
}

func (m *Defaults) GetWithDefault() int32 {
	if m != nil && m.WithDefault != nil {
		return *m.WithDefault
	}
	return 42
}

func (m *Defaults) HasWithDefault() bool {
	return m != nil && m.WithDefault != nil
}

func (m *Defaults) GetStrDefault() string {
	if m != nil && m.StrDefault != nil {
		return *m.StrDefault
	}
	return `hello`
}

func (m *Defaults) HasStrDefault() bool {
	return m != nil && m.StrDefault != nil
}

func (m *Defaults) GetBoolDefault() bool {
	if m != nil && m.BoolDefault != nil {
		return *m.BoolDefault
	}
	return true
}

func (m *Defaults) HasBoolDefault() bool {
	return m != nil && m.BoolDefault != nil
}

func (m *Defaults) GetEnumDefault() Role {
	if m != nil && m.EnumDefault != nil {
		return *m.EnumDefault
	}
	return Role_ADMIN
}

func (m *Defaults) HasEnumDefault() bool {
	return m != nil && m.EnumDefault != nil
}

func (m *Defaults) Size() (n int) {
	if m.WithDefault != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|0)) + protowire.SizeOfVarint(uint64(*m.WithDefault))
	}
	if m.StrDefault != nil {
		n += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.StrDefault))) + len(*m.StrDefault)
	}
	if m.BoolDefault != nil {
		n += protowire.SizeOfVarint(uint64(3<<3|0)) + 1
	}
	if m.EnumDefault != nil {
		n += protowire.SizeOfVarint(uint64(4<<3|0)) + protowire.SizeOfVarint(uint64(*m.EnumDefault))
	}
	return
}

func (m *Defaults) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.WithDefault != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.WithDefault))
	}
	if m.StrDefault != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.StrDefault)))
		copy(dAtA[i:], *m.StrDefault)
		i += len(*m.StrDefault)
	}
	if m.BoolDefault != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(3<<3|0))
		if *m.BoolDefault {
			dAtA[i] = 1
			i++
		} else {
			dAtA[i] = 0
			i++
		}
	}
	if m.EnumDefault != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(4<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.EnumDefault))
	}
	return i, nil
}

func (m *Defaults) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalDefaults(data []byte, ar *arena.Arena) (*Defaults, error) {
	m := arena.New[Defaults](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.WithDefault = protowire.Ptr(ar, int32(val))
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.StrDefault = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		case 3:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.BoolDefault = protowire.Ptr(ar, val != 0)
		case 4:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.EnumDefault = protowire.Ptr(ar, Role(val))
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type Repeated struct {
	UnpackedInt32 []int32
	Strings       []string
	PackedInt32   []int32
	PackedEnum    []Role
	Doubles       []float64
	ByteSlices    [][]byte
}

func (m *Repeated) GetUnpackedInt32() []int32 {
	if m != nil {
		return m.UnpackedInt32
	}
	return nil
}

func (m *Repeated) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *Repeated) GetPackedInt32() []int32 {
	if m != nil {
		return m.PackedInt32
	}
	return nil
}

func (m *Repeated) GetPackedEnum() []Role {
	if m != nil {
		return m.PackedEnum
	}
	return nil
}

func (m *Repeated) GetDoubles() []float64 {
	if m != nil {
		return m.Doubles
	}
	return nil
}

func (m *Repeated) GetByteSlices() [][]byte {
	if m != nil {
		return m.ByteSlices
	}
	return nil
}

func (m *Repeated) Size() (n int) {
	for _, v := range m.UnpackedInt32 {
		n += protowire.SizeOfVarint(uint64(1<<3|0)) + protowire.SizeOfVarint(uint64(v))
	}
	for _, v := range m.Strings {
		n += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(v))) + len(v)
	}
	if len(m.PackedInt32) > 0 {
		packedLen := 0
		for _, v := range m.PackedInt32 {
			packedLen += protowire.SizeOfVarint(uint64(v))
		}
		n += protowire.SizeOfVarint(uint64(3<<3|2)) + protowire.SizeOfVarint(uint64(packedLen)) + packedLen
	}
	if len(m.PackedEnum) > 0 {
		packedLen := 0
		for _, v := range m.PackedEnum {
			packedLen += protowire.SizeOfVarint(uint64(v))
		}
		n += protowire.SizeOfVarint(uint64(4<<3|2)) + protowire.SizeOfVarint(uint64(packedLen)) + packedLen
	}
	if len(m.Doubles) > 0 {
		packedLen := 0
		packedLen = len(m.Doubles) * 8
		n += protowire.SizeOfVarint(uint64(5<<3|2)) + protowire.SizeOfVarint(uint64(packedLen)) + packedLen
	}
	for _, v := range m.ByteSlices {
		n += protowire.SizeOfVarint(uint64(6<<3|2)) + protowire.SizeOfVarint(uint64(len(v))) + len(v)
	}
	return
}

func (m *Repeated) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	for _, v := range m.UnpackedInt32 {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(v))
	}
	for _, v := range m.Strings {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(v)))
		copy(dAtA[i:], v)
		i += len(v)
	}
	if len(m.PackedInt32) > 0 {
		i += protowire.EncodeVarint(dAtA[i:], uint64(3<<3|2))
		packedLen := 0
		for _, v := range m.PackedInt32 {
			packedLen += protowire.SizeOfVarint(uint64(v))
		}
		i += protowire.EncodeVarint(dAtA[i:], uint64(packedLen))
		for _, v := range m.PackedInt32 {
			i += protowire.EncodeVarint(dAtA[i:], uint64(v))
		}
	}
	if len(m.PackedEnum) > 0 {
		i += protowire.EncodeVarint(dAtA[i:], uint64(4<<3|2))
		packedLen := 0
		for _, v := range m.PackedEnum {
			packedLen += protowire.SizeOfVarint(uint64(v))
		}
		i += protowire.EncodeVarint(dAtA[i:], uint64(packedLen))
		for _, v := range m.PackedEnum {
			i += protowire.EncodeVarint(dAtA[i:], uint64(v))
		}
	}
	if len(m.Doubles) > 0 {
		i += protowire.EncodeVarint(dAtA[i:], uint64(5<<3|2))
		packedLen := 0
		packedLen = len(m.Doubles) * 8
		i += protowire.EncodeVarint(dAtA[i:], uint64(packedLen))
		for _, v := range m.Doubles {
			i += protowire.EncodeFixed64(dAtA[i:], math.Float64bits(v))
		}
	}
	for _, v := range m.ByteSlices {
		i += protowire.EncodeVarint(dAtA[i:], uint64(6<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(v)))
		copy(dAtA[i:], v)
		i += len(v)
	}
	return i, nil
}

func (m *Repeated) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalRepeated(data []byte, ar *arena.Arena) (*Repeated, error) {
	m := arena.New[Repeated](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			if wireType == 2 {
				length, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				end := i + int(length)
				for i < end {
					val, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					m.UnpackedInt32 = arena.Append(ar, m.UnpackedInt32, int32(val))
				}
			} else {
				val, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				m.UnpackedInt32 = arena.Append(ar, m.UnpackedInt32, int32(val))
			}
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Strings = arena.Append(ar, m.Strings, protowire.String(ar, data[i:i+int(length)]))
			i += int(length)
		case 3:
			if wireType == 2 {
				length, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				end := i + int(length)
				for i < end {
					val, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					m.PackedInt32 = arena.Append(ar, m.PackedInt32, int32(val))
				}
			} else {
				val, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				m.PackedInt32 = arena.Append(ar, m.PackedInt32, int32(val))
			}
		case 4:
			if wireType == 2 {
				length, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				end := i + int(length)
				for i < end {
					val, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					m.PackedEnum = arena.Append(ar, m.PackedEnum, Role(val))
				}
			} else {
				val, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				m.PackedEnum = arena.Append(ar, m.PackedEnum, Role(val))
			}
		case 5:
			if wireType == 2 {
				length, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				end := i + int(length)
				for i < end {
					val, n, err := protowire.DecodeFixed64(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					m.Doubles = arena.Append(ar, m.Doubles, math.Float64frombits(val))
				}
			} else {
				val, n, err := protowire.DecodeFixed64(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				m.Doubles = arena.Append(ar, m.Doubles, math.Float64frombits(val))
			}
		case 6:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.ByteSlices = arena.Append(ar, m.ByteSlices, ar.Bytes(data[i:i+int(length)]))
			i += int(length)
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type Inner struct {
	Name  *string
	Value *int32
}

func (m *Inner) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Inner) HasName() bool {
	return m != nil && m.Name != nil
}

func (m *Inner) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Inner) HasValue() bool {
	return m != nil && m.Value != nil
}

func (m *Inner) Size() (n int) {
	if m.Name != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.Name))) + len(*m.Name)
	}
	if m.Value != nil {
		n += protowire.SizeOfVarint(uint64(2<<3|0)) + protowire.SizeOfVarint(uint64(*m.Value))
	}
	return
}

func (m *Inner) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Name != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.Name)))
		copy(dAtA[i:], *m.Name)
		i += len(*m.Name)
	}
	if m.Value != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.Value))
	}
	return i, nil
}

func (m *Inner) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalInner(data []byte, ar *arena.Arena) (*Inner, error) {
	m := arena.New[Inner](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Name = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		case 2:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Value = protowire.Ptr(ar, int32(val))
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type Middle struct {
	Inner *Inner
	Label *string
}

func (m *Middle) GetInner() *Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *Middle) HasInner() bool {
	return m != nil && m.Inner != nil
}

func (m *Middle) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Middle) HasLabel() bool {
	return m != nil && m.Label != nil
}

func (m *Middle) Size() (n int) {
	if m.Inner != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(m.Inner.Size())) + m.Inner.Size()
	}
	if m.Label != nil {
		n += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.Label))) + len(*m.Label)
	}
	return
}

func (m *Middle) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Inner != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(m.Inner.Size()))
		m.Inner.MarshalTo(dAtA[i:])
		i += m.Inner.Size()
	}
	if m.Label != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.Label)))
		copy(dAtA[i:], *m.Label)
		i += len(*m.Label)
	}
	return i, nil
}

func (m *Middle) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalMiddle(data []byte, ar *arena.Arena) (*Middle, error) {
	m := arena.New[Middle](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			msgLen, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			msg, err := UnmarshalInner(data[i:i+int(msgLen)], ar)
			if err != nil {
				return nil, err
			}
			m.Inner = msg
			i += int(msgLen)
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Label = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type Outer struct {
	Middle *Middle
	Tag    *string
}

func (m *Outer) GetMiddle() *Middle {
	if m != nil {
		return m.Middle
	}
	return nil
}

func (m *Outer) HasMiddle() bool {
	return m != nil && m.Middle != nil
}

func (m *Outer) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Outer) HasTag() bool {
	return m != nil && m.Tag != nil
}

func (m *Outer) Size() (n int) {
	if m.Middle != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(m.Middle.Size())) + m.Middle.Size()
	}
	if m.Tag != nil {
		n += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.Tag))) + len(*m.Tag)
	}
	return
}

func (m *Outer) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Middle != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(m.Middle.Size()))
		m.Middle.MarshalTo(dAtA[i:])
		i += m.Middle.Size()
	}
	if m.Tag != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.Tag)))
		copy(dAtA[i:], *m.Tag)
		i += len(*m.Tag)
	}
	return i, nil
}

func (m *Outer) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalOuter(data []byte, ar *arena.Arena) (*Outer, error) {
	m := arena.New[Outer](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			msgLen, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			msg, err := UnmarshalMiddle(data[i:i+int(msgLen)], ar)
			if err != nil {
				return nil, err
			}
			m.Middle = msg
			i += int(msgLen)
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Tag = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type Maps struct {
	StringInt32  *arena.Map[string, int32]
	StringString *arena.Map[string, string]
	Int32Msg     *arena.Map[int32, *Inner]
}

func (m *Maps) GetStringInt32() *arena.Map[string, int32] {
	if m != nil {
		return m.StringInt32
	}
	return nil
}

func (m *Maps) GetStringString() *arena.Map[string, string] {
	if m != nil {
		return m.StringString
	}
	return nil
}

func (m *Maps) GetInt32Msg() *arena.Map[int32, *Inner] {
	if m != nil {
		return m.Int32Msg
	}
	return nil
}

func (m *Maps) Size() (n int) {
	if m.StringInt32 != nil {
		m.StringInt32.All()(func(k string, v int32) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(1<<3 | 2))
			entrySize += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(k))) + len(k)
			entrySize += protowire.SizeOfVarint(uint64(2<<3|0)) + protowire.SizeOfVarint(uint64(vv))
			n += entrySize + protowire.SizeOfVarint(uint64(entrySize))
			return true
		})
	}
	if m.StringString != nil {
		m.StringString.All()(func(k string, v string) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(2<<3 | 2))
			entrySize += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(k))) + len(k)
			entrySize += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(vv))) + len(vv)
			n += entrySize + protowire.SizeOfVarint(uint64(entrySize))
			return true
		})
	}
	if m.Int32Msg != nil {
		m.Int32Msg.All()(func(k int32, v *Inner) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(3<<3 | 2))
			entrySize += protowire.SizeOfVarint(uint64(1<<3|0)) + protowire.SizeOfVarint(uint64(k))
			entrySize += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(vv.Size())) + vv.Size()
			n += entrySize + protowire.SizeOfVarint(uint64(entrySize))
			return true
		})
	}
	return
}

func (m *Maps) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.StringInt32 != nil {
		m.StringInt32.All()(func(k string, v int32) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(k))) + len(k) + protowire.SizeOfVarint(uint64(2<<3|0)) + protowire.SizeOfVarint(uint64(vv))
			i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(entrySize))
			i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(len(k)))
			copy(dAtA[i:], k)
			i += len(k)
			i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|0))
			i += protowire.EncodeVarint(dAtA[i:], uint64(vv))
			return true
		})
	}
	if m.StringString != nil {
		m.StringString.All()(func(k string, v string) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(k))) + len(k) + protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(vv))) + len(vv)
			i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(entrySize))
			i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(len(k)))
			copy(dAtA[i:], k)
			i += len(k)
			i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(len(vv)))
			copy(dAtA[i:], vv)
			i += len(vv)
			return true
		})
	}
	if m.Int32Msg != nil {
		m.Int32Msg.All()(func(k int32, v *Inner) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(1<<3|0)) + protowire.SizeOfVarint(uint64(k)) + protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(vv.Size())) + vv.Size()
			i += protowire.EncodeVarint(dAtA[i:], uint64(3<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(entrySize))
			i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|0))
			i += protowire.EncodeVarint(dAtA[i:], uint64(k))
			i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(vv.Size()))
			vv.MarshalTo(dAtA[i:])
			i += vv.Size()
			return true
		})
	}
	return i, nil
}

func (m *Maps) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalMaps(data []byte, ar *arena.Arena) (*Maps, error) {
	m := arena.New[Maps](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			end := i + int(length)
			var mk string
			var mv int32
			for i < end {
				tag, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				fieldNum := int(tag >> 3)
				switch fieldNum {
				case 1:
					length, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mk = protowire.String(ar, data[i:i+int(length)])
					i += int(length)
				case 2:
					val, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mv = int32(val)
				default:
					skipped, err := protowire.SkipField(data[i:], int(tag&7))
					if err != nil {
						return nil, err
					}
					i += skipped
				}
			}
			if m.StringInt32 == nil {
				m.StringInt32 = arena.NewMap[string, int32](ar, 0)
			}
			m.StringInt32.Put(mk, mv)
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			end := i + int(length)
			var mk string
			var mv string
			for i < end {
				tag, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				fieldNum := int(tag >> 3)
				switch fieldNum {
				case 1:
					length, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mk = protowire.String(ar, data[i:i+int(length)])
					i += int(length)
				case 2:
					length, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mv = protowire.String(ar, data[i:i+int(length)])
					i += int(length)
				default:
					skipped, err := protowire.SkipField(data[i:], int(tag&7))
					if err != nil {
						return nil, err
					}
					i += skipped
				}
			}
			if m.StringString == nil {
				m.StringString = arena.NewMap[string, string](ar, 0)
			}
			m.StringString.Put(mk, mv)
		case 3:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			end := i + int(length)
			var mk int32
			var mv *Inner
			for i < end {
				tag, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				fieldNum := int(tag >> 3)
				switch fieldNum {
				case 1:
					val, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mk = int32(val)
				case 2:
					msgLen, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					msg, err := UnmarshalInner(data[i:i+int(msgLen)], ar)
					if err != nil {
						return nil, err
					}
					mv = msg
					i += int(msgLen)
				default:
					skipped, err := protowire.SkipField(data[i:], int(tag&7))
					if err != nil {
						return nil, err
					}
					i += skipped
				}
			}
			if m.Int32Msg == nil {
				m.Int32Msg = arena.NewMap[int32, *Inner](ar, 0)
			}
			m.Int32Msg.Put(mk, mv)
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type isOneofMsg_Choice interface{ isOneofMsg_Choice() }
type OneofMsg_StrVal struct{ Value string }

func (*OneofMsg_StrVal) isOneofMsg_Choice() {}

type OneofMsg_BytesVal struct{ Value []byte }

func (*OneofMsg_BytesVal) isOneofMsg_Choice() {}

type OneofMsg_MsgVal struct{ Value *Inner }

func (*OneofMsg_MsgVal) isOneofMsg_Choice() {}

type OneofMsg_IntVal struct{ Value int32 }

func (*OneofMsg_IntVal) isOneofMsg_Choice() {}

type OneofMsg struct {
	Name   *string
	Choice isOneofMsg_Choice
}

func (m *OneofMsg) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *OneofMsg) HasName() bool {
	return m != nil && m.Name != nil
}

func (m *OneofMsg) GetStrVal() string {
	if x, ok := m.Choice.(*OneofMsg_StrVal); ok {
		return x.Value
	}
	return ""
}

func (m *OneofMsg) GetBytesVal() []byte {
	if x, ok := m.Choice.(*OneofMsg_BytesVal); ok {
		return x.Value
	}
	return nil
}

func (m *OneofMsg) GetMsgVal() *Inner {
	if x, ok := m.Choice.(*OneofMsg_MsgVal); ok {
		return x.Value
	}
	return nil
}

func (m *OneofMsg) GetIntVal() int32 {
	if x, ok := m.Choice.(*OneofMsg_IntVal); ok {
		return x.Value
	}
	return 0
}

func (m *OneofMsg) Size() (n int) {
	if m.Name != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.Name))) + len(*m.Name)
	}
	switch x := m.Choice.(type) {
	case *OneofMsg_StrVal:
		n += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(x.Value))) + len(x.Value)
	case *OneofMsg_BytesVal:
		n += protowire.SizeOfVarint(uint64(3<<3|2)) + protowire.SizeOfVarint(uint64(len(x.Value))) + len(x.Value)
	case *OneofMsg_MsgVal:
		n += protowire.SizeOfVarint(uint64(4<<3|2)) + protowire.SizeOfVarint(uint64(x.Value.Size())) + x.Value.Size()
	case *OneofMsg_IntVal:
		n += protowire.SizeOfVarint(uint64(5<<3|0)) + protowire.SizeOfVarint(uint64(x.Value))
	default:
		_ = x
	}
	return
}

func (m *OneofMsg) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Name != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.Name)))
		copy(dAtA[i:], *m.Name)
		i += len(*m.Name)
	}
	switch x := m.Choice.(type) {
	case *OneofMsg_StrVal:
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(x.Value)))
		copy(dAtA[i:], x.Value)
		i += len(x.Value)
	case *OneofMsg_BytesVal:
		i += protowire.EncodeVarint(dAtA[i:], uint64(3<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(x.Value)))
		copy(dAtA[i:], x.Value)
		i += len(x.Value)
	case *OneofMsg_MsgVal:
		i += protowire.EncodeVarint(dAtA[i:], uint64(4<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(x.Value.Size()))
		x.Value.MarshalTo(dAtA[i:])
		i += x.Value.Size()
	case *OneofMsg_IntVal:
		i += protowire.EncodeVarint(dAtA[i:], uint64(5<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(x.Value))
	default:
		_ = x
	}
	return i, nil
}

func (m *OneofMsg) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalOneofMsg(data []byte, ar *arena.Arena) (*OneofMsg, error) {
	m := arena.New[OneofMsg](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Name = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			w := arena.New[OneofMsg_StrVal](ar)
			w.Value = protowire.String(ar, data[i:i+int(length)])
			m.Choice = w
			i += int(length)
		case 3:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			w := arena.New[OneofMsg_BytesVal](ar)
			w.Value = ar.Bytes(data[i : i+int(length)])
			m.Choice = w
			i += int(length)
		case 4:
			msgLen, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			msg, err := UnmarshalInner(data[i:i+int(msgLen)], ar)
			if err != nil {
				return nil, err
			}
			w := arena.New[OneofMsg_MsgVal](ar)
			w.Value = msg
			m.Choice = w
			i += int(msgLen)
		case 5:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			w := arena.New[OneofMsg_IntVal](ar)
			w.Value = int32(val)
			m.Choice = w
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}

type isFullMessage_Payload interface{ isFullMessage_Payload() }
type FullMessage_TextPayload struct{ Value string }

func (*FullMessage_TextPayload) isFullMessage_Payload() {}

type FullMessage_BinaryPayload struct{ Value []byte }

func (*FullMessage_BinaryPayload) isFullMessage_Payload() {}

type FullMessage struct {
	Id      *int32
	Label   *string
	Tags    []string
	Scores  *arena.Map[string, int32]
	Nested  *Inner
	Role    *Role
	Payload isFullMessage_Payload
}

func (m *FullMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *FullMessage) HasId() bool {
	return m != nil && m.Id != nil
}

func (m *FullMessage) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *FullMessage) HasLabel() bool {
	return m != nil && m.Label != nil
}

func (m *FullMessage) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *FullMessage) GetScores() *arena.Map[string, int32] {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *FullMessage) GetNested() *Inner {
	if m != nil {
		return m.Nested
	}
	return nil
}

func (m *FullMessage) HasNested() bool {
	return m != nil && m.Nested != nil
}

func (m *FullMessage) GetRole() Role {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return Role_UNKNOWN
}

func (m *FullMessage) HasRole() bool {
	return m != nil && m.Role != nil
}

func (m *FullMessage) GetTextPayload() string {
	if x, ok := m.Payload.(*FullMessage_TextPayload); ok {
		return x.Value
	}
	return ""
}

func (m *FullMessage) GetBinaryPayload() []byte {
	if x, ok := m.Payload.(*FullMessage_BinaryPayload); ok {
		return x.Value
	}
	return nil
}

func (m *FullMessage) Size() (n int) {
	if m.Id != nil {
		n += protowire.SizeOfVarint(uint64(1<<3|0)) + protowire.SizeOfVarint(uint64(*m.Id))
	}
	if m.Label != nil {
		n += protowire.SizeOfVarint(uint64(2<<3|2)) + protowire.SizeOfVarint(uint64(len(*m.Label))) + len(*m.Label)
	}
	for _, v := range m.Tags {
		n += protowire.SizeOfVarint(uint64(3<<3|2)) + protowire.SizeOfVarint(uint64(len(v))) + len(v)
	}
	if m.Scores != nil {
		m.Scores.All()(func(k string, v int32) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(4<<3 | 2))
			entrySize += protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(k))) + len(k)
			entrySize += protowire.SizeOfVarint(uint64(2<<3|0)) + protowire.SizeOfVarint(uint64(vv))
			n += entrySize + protowire.SizeOfVarint(uint64(entrySize))
			return true
		})
	}
	if m.Nested != nil {
		n += protowire.SizeOfVarint(uint64(5<<3|2)) + protowire.SizeOfVarint(uint64(m.Nested.Size())) + m.Nested.Size()
	}
	if m.Role != nil {
		n += protowire.SizeOfVarint(uint64(6<<3|0)) + protowire.SizeOfVarint(uint64(*m.Role))
	}
	switch x := m.Payload.(type) {
	case *FullMessage_TextPayload:
		n += protowire.SizeOfVarint(uint64(7<<3|2)) + protowire.SizeOfVarint(uint64(len(x.Value))) + len(x.Value)
	case *FullMessage_BinaryPayload:
		n += protowire.SizeOfVarint(uint64(8<<3|2)) + protowire.SizeOfVarint(uint64(len(x.Value))) + len(x.Value)
	default:
		_ = x
	}
	return
}

func (m *FullMessage) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Id != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.Id))
	}
	if m.Label != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(*m.Label)))
		copy(dAtA[i:], *m.Label)
		i += len(*m.Label)
	}
	for _, v := range m.Tags {
		i += protowire.EncodeVarint(dAtA[i:], uint64(3<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(v)))
		copy(dAtA[i:], v)
		i += len(v)
	}
	if m.Scores != nil {
		m.Scores.All()(func(k string, v int32) bool {
			vv := v
			entrySize := protowire.SizeOfVarint(uint64(1<<3|2)) + protowire.SizeOfVarint(uint64(len(k))) + len(k) + protowire.SizeOfVarint(uint64(2<<3|0)) + protowire.SizeOfVarint(uint64(vv))
			i += protowire.EncodeVarint(dAtA[i:], uint64(4<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(entrySize))
			i += protowire.EncodeVarint(dAtA[i:], uint64(1<<3|2))
			i += protowire.EncodeVarint(dAtA[i:], uint64(len(k)))
			copy(dAtA[i:], k)
			i += len(k)
			i += protowire.EncodeVarint(dAtA[i:], uint64(2<<3|0))
			i += protowire.EncodeVarint(dAtA[i:], uint64(vv))
			return true
		})
	}
	if m.Nested != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(5<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(m.Nested.Size()))
		m.Nested.MarshalTo(dAtA[i:])
		i += m.Nested.Size()
	}
	if m.Role != nil {
		i += protowire.EncodeVarint(dAtA[i:], uint64(6<<3|0))
		i += protowire.EncodeVarint(dAtA[i:], uint64(*m.Role))
	}
	switch x := m.Payload.(type) {
	case *FullMessage_TextPayload:
		i += protowire.EncodeVarint(dAtA[i:], uint64(7<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(x.Value)))
		copy(dAtA[i:], x.Value)
		i += len(x.Value)
	case *FullMessage_BinaryPayload:
		i += protowire.EncodeVarint(dAtA[i:], uint64(8<<3|2))
		i += protowire.EncodeVarint(dAtA[i:], uint64(len(x.Value)))
		copy(dAtA[i:], x.Value)
		i += len(x.Value)
	default:
		_ = x
	}
	return i, nil
}

func (m *FullMessage) Marshal() ([]byte, error) {
	buf := make([]byte, m.Size())
	n, err := m.MarshalTo(buf)
	if err != nil {
		return nil, err
	}
	return buf[:n], nil
}

func UnmarshalFullMessage(data []byte, ar *arena.Arena) (*FullMessage, error) {
	m := arena.New[FullMessage](ar)
	i := 0
	for i < len(data) {
		tag, n, err := protowire.DecodeVarint(data[i:])
		if err != nil {
			return nil, err
		}
		i += n
		fieldNum := int(tag >> 3)
		wireType := int(tag & 7)
		switch fieldNum {
		case 1:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Id = protowire.Ptr(ar, int32(val))
		case 2:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Label = protowire.StringPtr(ar, data[i:i+int(length)])
			i += int(length)
		case 3:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Tags = arena.Append(ar, m.Tags, protowire.String(ar, data[i:i+int(length)]))
			i += int(length)
		case 4:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			end := i + int(length)
			var mk string
			var mv int32
			for i < end {
				tag, n, err := protowire.DecodeVarint(data[i:])
				if err != nil {
					return nil, err
				}
				i += n
				fieldNum := int(tag >> 3)
				switch fieldNum {
				case 1:
					length, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mk = protowire.String(ar, data[i:i+int(length)])
					i += int(length)
				case 2:
					val, n, err := protowire.DecodeVarint(data[i:])
					if err != nil {
						return nil, err
					}
					i += n
					mv = int32(val)
				default:
					skipped, err := protowire.SkipField(data[i:], int(tag&7))
					if err != nil {
						return nil, err
					}
					i += skipped
				}
			}
			if m.Scores == nil {
				m.Scores = arena.NewMap[string, int32](ar, 0)
			}
			m.Scores.Put(mk, mv)
		case 5:
			msgLen, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			msg, err := UnmarshalInner(data[i:i+int(msgLen)], ar)
			if err != nil {
				return nil, err
			}
			m.Nested = msg
			i += int(msgLen)
		case 6:
			val, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			m.Role = protowire.Ptr(ar, Role(val))
		case 7:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			w := arena.New[FullMessage_TextPayload](ar)
			w.Value = protowire.String(ar, data[i:i+int(length)])
			m.Payload = w
			i += int(length)
		case 8:
			length, n, err := protowire.DecodeVarint(data[i:])
			if err != nil {
				return nil, err
			}
			i += n
			w := arena.New[FullMessage_BinaryPayload](ar)
			w.Value = ar.Bytes(data[i : i+int(length)])
			m.Payload = w
			i += int(length)
		default:
			skipped, err := protowire.SkipField(data[i:], wireType)
			if err != nil {
				return nil, err
			}
			i += skipped
		}
	}
	return m, nil
}
